"""竞彩中文名 → BSD 英文关键词。只用于对齐，不是展示名。"""
from __future__ import annotations

# (竞彩别名, bsd 匹配关键词)
TEAM_SEEDS = [
    ("巴塞罗那", "barcelona"), ("巴萨", "barcelona"),
    ("皇马", "real madrid"), ("皇家马德里", "real madrid"),
    ("马竞", "atletico madrid"), ("马德里竞技", "atletico madrid"),
    ("马拉加", "malaga"), ("塞维利亚", "sevilla"),
    ("贝蒂斯", "betis"), ("皇家贝蒂斯", "betis"), ("赫塔费", "getafe"),
    ("毕尔巴鄂", "athletic"), ("毕尔巴鄂竞技", "athletic"),
    ("皇家社会", "real sociedad"), ("瓦伦西亚", "valencia"),
    ("比利亚雷亚尔", "villarreal"), ("比利亚雷", "villarreal"),
    ("塞尔塔", "celta"), ("奥萨苏纳", "osasuna"), ("西班牙人", "espanyol"),
    ("阿拉维斯", "alaves"), ("莱万特", "levante"), ("埃尔切", "elche"),
    ("拉科鲁尼亚", "deportivo"), ("拉科", "deportivo"),
    ("巴列卡诺", "rayo"), ("桑坦德", "racing"),
    ("曼城", "manchester city"), ("曼联", "manchester united"),
    ("利物浦", "liverpool"), ("切尔西", "chelsea"), ("阿森纳", "arsenal"),
    ("热刺", "tottenham"), ("纽卡斯尔", "newcastle"), ("维拉", "villa"),
    ("布莱顿", "brighton"), ("考文垂", "coventry"),
    ("水晶宫", "crystal palace"), ("伯恩茅斯", "bournemouth"),
    ("桑德兰", "sunderland"),
    ("尤文图斯", "juventus"), ("国际米兰", "inter"), ("AC米兰", "milan"),
    ("那不勒斯", "napoli"), ("罗马", "roma"), ("拉齐奥", "lazio"),
    ("亚特兰大", "atalanta"), ("佛罗伦萨", "fiorentina"),
    ("拜仁", "bayern"), ("多特蒙德", "dortmund"), ("勒沃库森", "leverkusen"),
    ("霍芬海姆", "hoffenheim"),
    ("巴黎圣日耳曼", "paris"), ("阿贾克斯", "ajax"),
    ("埃因霍温", "psv"), ("费耶诺德", "feyenoord"), ("阿尔克马", "alkmaar"),
    ("本菲卡", "benfica"), ("波尔图", "porto"), ("里斯本竞技", "sporting"),
    ("凯尔特人", "celtic"), ("里昂", "lyon"), ("马赛", "marseille"),
    ("雷恩", "rennes"), ("安德莱", "anderlecht"), ("贝西克塔", "besiktas"),
    ("奈梅亨", "nijmegen"), ("奥莫尼亚", "omonia"), ("克里特", "crete"),
    ("采列", "celje"), ("波兹南", "poznan"), ("利勒斯特", "lillestrom"),
    ("托林斯", "torreense"), ("格风暴", "sturm"), ("格拉茨风暴", "sturm"),
    ("博塔弗戈", "botafogo"), ("格雷米奥", "gremio"), ("帕梅拉斯", "palmeiras"),
    ("弗拉门戈", "flamengo"), ("科林蒂安", "corinthians"), ("基多体大", "ldu"),
    ("拉普大学", "estudiantes"), ("德尔瓦耶", "independiente del valle"),
    ("浙江", "zhejiang"), ("武汉三镇", "wuhan"), ("上海申花", "shenhua"),
    ("上海海港", "shanghai port"), ("山东泰山", "shandong"),
    ("北京国安", "guoan"), ("成都蓉城", "chengdu"), ("河南", "henan"),
    ("天津津门虎", "tianjin"),
    ("川崎前锋", "kawasaki"), ("鹿岛鹿角", "kashima"), ("浦和红钻", "urawa"),
    ("横滨水手", "yokohama"), ("大阪钢巴", "gamba"), ("大阪樱花", "cerezo"),
    ("名古屋鲸", "nagoya"), ("名古屋鲸鱼", "nagoya"),
    ("FC东京", "tokyo"), ("东京FC", "tokyo"), ("神户胜利船", "vissel"),
    ("广岛三箭", "sanfrecce"), ("福冈黄蜂", "avispa"),
    ("町田泽维亚", "machida"), ("柏太阳神", "kashiwa"),
    ("清水心跳", "shimizu"), ("京都", "kyoto"),
    ("长崎成功丸", "nagasaki"), ("冈山绿雉", "okayama"),
    ("东京绿茵", "verdy"), ("千叶市原", "jef"), ("水户蜀葵", "mito"),
]
